### ISSUE TITLE
Check restructured text conversion results for Nexus

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-rackconnect#13]
# Nexus conversion quality check

1. After downloading the restructured text files to your system, make sure the content builds. For instrucutions, see the [Contributors Guide](https://github.com/rackerlabs/docs-migration/blob/master/tools/author-guide-to-converted-docs.rst). 
2. Complete the quality checks, fixing any issues that come up. 
3. Rebuild content and resolve build errors.
3. Push updated source to github.

## Get help
- Chat about problems or issues you discover in the [devdoc-migration Slack channel](https://rackdx.slack.com/messages/devdoc-migration)
- Find resources for learning and using restructured text in the [Author's Guide](https://github.com/rackerlabs/docs-migration/blob/master/tools/author-guide-to-converted-docs.rst) and  the [Developer Documentation wiki](https://one.rackspace.com/display/devdoc/RST).

## Notes
-  Ignore authentication section with callouts. Will be replaced with common content.
- For cross-devguide links, API operation links, or links to other content still on docs.rackspace.com:  Leave them pointing to docs.rackspace.com for now.  After we determine the repo structure and have a better linking strategy, we can fix these links. 

## Quality Checklist
Here's a general checklist for reviewing the converted documentation.  If something is missing, or you encounter a strange problem, discuss it in Slack.

- [x] Compare content to docs.rackspace.com
       - All sections included.
       - Investigate and fix missing information.
       -  Add information updates since conversion. 
- [x] Check and fix broken internal, inter-book, and external links
       -      When possible, make links inline with text, not a separate sentence.
       -      Fix cross-reference links as required.  -- Might have to add a anchor ID to section linking to.
       -      External links should be called out at bottom of section. 
       -      Links to other devguides or api operations -- use docs.rackspace.com references for now.  We will have to update later when linking strategy and source storage location has been determined. 
- [x] Check code sample format
     -	     Alignment
     -	     Make sure the code sample doesn't include body text.
     -	     Look for stray characters at end of code samples 
- [x] Check for formatting issues in paragraphs, lists, tables, and so on.
      -	     Often caused by incorrect alignment on indents.
      -	     Missing blank line between format changes.  For example, after a table, figure, or code example title, include a blank line.
- [x] Check inline literals for correct format. 
      - Require double backquotes to render `` `` 
      - Include space before the first set of back quotes, and after the second set of back quotes.
      - Sometimes you might have to escape after a backquote to get things to render correctly.

**Comment by DonNateR** [comment]
This is done, closing issue.
