### ISSUE TITLE
Missing Content? Retrieving Authentication token

### ISSUE THREAD

**Issue by lauracly** [rackerlabs/docs-cloud-rackconnect#30]
This topic is missing on staging: http://docs.rackspace.com/rackconnect/api/v3/rackconnect-devguide/content/Retrieving_the_auth_token.html

was this done on purpose? Please check and confirm.

**Comment by stanzikratel** [comment]
@lauracly This was removed as a part of the common content rewriting effort. Nate, who converted RackConnect rearranged some of the common content and taking this topic out was part of rearranging the content
