### ISSUE TITLE
Added Content? List nodes in one load balancer pool

### ISSUE THREAD

**Issue by lauracly** [rackerlabs/docs-cloud-rackconnect#32]
There are three additional topics under Load Balancer Pools that don't appear in the V3 version on docs. They are:
List the nodes in one load balancer pool:http://staging.developer.rackspace.com/docs-cloud-rackconnect/#list-the-nodes-in-one-load-balancer-pool
Show details for one load balancer pool: http://staging.developer.rackspace.com/docs-cloud-rackconnect/#show-details-for-one-load-balancer-pool
Add node to load balancer pool: http://staging.developer.rackspace.com/docs-cloud-rackconnect/#add-node-to-load-balancer-pool

Check that these topics should be a part of this guide.

**Comment by catlook** [comment]
These are in the apiary docs now.
