### ISSUE TITLE
RackConnect v3 docs missing several API calls

### ISSUE THREAD

**Issue by inflatador** [rackerlabs/docs-cloud-rackconnect#64]
### Report an issue with the documentation

Describe your documentation issue in  the relevant section. Submit product operation or 
performance issues to the Rackspace product team at https://feedback.rackspace.com/.

**Link to documentation with issue:**  

https://developer.rackspace.com/docs/rackconnect/v3/developer-guide/

**Report editorial or format problem:** 

**Report incorrect information:**

**Report missing information:**

Lacks some RCv3 API calls, looks like the source of truth for RCv3 API is https://rcv3.docs.apiary.io/

**Documentation feedback:**
Hit me back on slack or email and I can provide more specifics, if necessary.

**Comment by catlook** [comment]
I've forwarded this to the rackconnect team.  It looks like this repo is not published on our landing page and is not being kept up to date.  the Apiary doc, which is on the landing page, is maintained by the rackconnect team.  If anything is missing on that doc, that team can address the issue!  They said they want to start using infodev-style docs again, so this may get resurrected.  If so, will make sure all ops are accounted for at that time!
